# Generated by Django 2.1.1 on 2018-09-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180916_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null='True', upload_to='static/uploads'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null='True', upload_to='static/uploads'),
        ),
    ]
