# Generated by Django 2.1.1 on 2018-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180916_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null='True', upload_to='category/uploads'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null='True', upload_to='items/uploads'),
        ),
    ]
